### ISSUE TITLE
Enabling notifications

### ISSUE THREAD

**Issue by jtebert** [2BWorks/OctoPrint-3DGeeks#1]
The instructions say, "Enable remote notifications from within the app," but I can't seem to find that anywhere within the Android app. It might be useful to clarify the instructions, because without that, sending the test notification from Octoprint doesn't give me a notification.

**Comment by tobyworks** [comment]
Hi! Please make sure you have installed the latest version of 3D Geeks (1.14)

**Comment by 2BWorks** [comment]
Hi! Please make sure you have installed the latest version of 3D Geeks (1.14). You can enable the checkbox when you are setting up your octoprint instance in the app. (Settings -> OctoPrint Settings -> + -> Scan QR )
